# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "1220523a3a301cbfbd83a374e2a69073fa14b211f2f6aaa4fc9497c936feaa67f738";
    path = fetchzip {
      url = "https://github.com/rockorager/libvaxis/archive/v0.4.1/f0eaa3c831f6376e7fa0519c275cdcb764580e12.tar.gz";
      hash = "sha256-UTpv0cdb98RU48Rc0z3AvYO6SDXsKJMFrwm10of6nCE=";
    };
  }
]
